/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fetcher(input: string): string
export function plus100(input: number): number
export function plus101(input: number): number
export function plus100String(input: number): string
